### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by brentp** [kaist-ina/BWA-MEME#1]
is the LICENSE file in the repo for bwa-meme? (It appears to be for bwa-mem2). 
What is the exact license for bwa-meme? thanks.

**Comment by quito418** [comment]
Hi,

BWA-MEME source code is distributed under the MIT Licence.

I will update the License file.

Thank you!

**Comment by jmarshall** [comment]
Thank you for clarifying the licence file.

The MIT licence says (emphasis added)

> Permission is hereby granted […] to **any person** […] to deal in the Software without restriction, including without limitation the rights to use […]

However the repository's _README.md_ file says

> The source code and test scripts are available for academic use

These two statements would appear to be contradictory.

**Comment by quito418** [comment]
> Thank you for clarifying the licence file.
> 
> The MIT licence says (emphasis added)
> 
> > Permission is hereby granted […] to **any person** […] to deal in the Software without restriction, including without limitation the rights to use […]
> 
> However the repository's _README.md_ file says
> 
> > The source code and test scripts are available for academic use
> 
> These two statements would appear to be contradictory.

We updated the Readme, you can freely use the code.

Thank you
