### ISSUE TITLE
compile error while building locally

### ISSUE THREAD

**Issue by AdilyAid** [kaist-ina/BWA-MEME#11]
Hello, 

After git cloning the code, I run: `make -j32 `and got:

```
...
In file included from src/bwtindex.cpp:43:
src/Learnedindex.h:35:27: note:   initializing argument 1 of ‘void buildSAandLEP(char*, int)’
   35 | void buildSAandLEP( char* prefix,  int num_threads);
      |                     ~~~~~~^~~~~~
src/bwamem_pair.cpp: In function ‘int mem_matesw_batch_pre(const mem_opt_t*, const bntseq_t*, const uint8_t*, const mem_pestat_t*, const mem_alnreg_t*, int, const uint8_t*, mem_alnreg_v*, mem_cache*, int, int32_t, int32_t&, int32_t&, int32_t)’:
src/bwamem_pair.cpp:1158:33: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
 1158 |                 fprintf(stderr, "[0000][%0.4d] Re-allocating (doubling) seqBufRefs in %s\n",
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bwamem_pair.cpp:1175:33: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
 1175 |                 fprintf(stderr, "[0000][%0.4d] Re-allocating (doubling) seqBufQers in %s\n",
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bwamem_pair.cpp:1192:33: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
 1192 |                 fprintf(stderr, "[0000][%0.4d] Re-allocating seqPairs in %s\n", tid, __func__);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/user/soft/BWA-MEME'
make: *** [Makefile:123: multi] Error 2
```
gcc version is 9.4.0, ubuntu1~20.04.1
What can be the problem?

Thank you in advance,
Adily

**Comment by quito418** [comment]
Hi Adily,

Thank you for reporting the error.

To figure out where error occur, I need the whole error output.

Could you share the whole compile log file? (you can do this by below command)
`make -j 32 2> error.log`

**Comment by AdilyAid** [comment]
[error.log](https://github.com/kaist-ina/BWA-MEME/files/9196427/error.log)

The error log is attached. Thank you for your help!

**Comment by quito418** [comment]
I see `cmake` is not available on your server.

Can you try compiling after installing `cmake` with the below command?
`sudo apt install cmake`

**Comment by AdilyAid** [comment]
Thank you very much! that was the problem. Solved!

Now I got another error when execute the command `./build_rmis_dna.sh db_adaptors.fasta`:
```
Training top-level pwl model layer
Training second-level linear model layer (num models = 268435456)
/home/user/soft/BWA-MEME/build_rmis_dna.sh: line 39: 3225052 Killed                  bwa-meme-train-prmi --data-path $DIR_NAME $DATA_PATH $DATA_NAME pwl,linear,linear_spline 268435456
```

**Comment by quito418** [comment]
I suspect that the process is getting killed because of the memory limitation in your server.

For human reference, I remember it takes around 80GB of memory.  (Depending on the mode the size of the server memory would not be enough to run BWA-MEME)

if you like to proceed anyway, you might want to use a swap memory to build the index. [making swap memory](https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-20-04/)

**Comment by AdilyAid** [comment]
My reference is small, 8 sequences, each of them 45 bp. 
Is it make sense the memory limitation is the problem in this case?

**Comment by quito418** [comment]
Oh, I see memory might not be the cause here. 

In case you are checking out the speed, you can use [small reference file](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/blob/cabdab1ba32ca66fa6ed730999cce857e02bebcc/demo/ref.fa) (I checked our code works with this reference and it does not require much memory or time).

if you want to use your reference file, could you share the file for me to debug the issue?

**Comment by AdilyAid** [comment]
I could not upload fasta file here so I paste the sequences:

>left_to_insert_db_1_A
GTACATGAATCATACGGTGAACTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_1_T
GTACATGAATCATACGGTGATCTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_1_G
GTACATGAATCATACGGTGAGCTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_1_C
GTACATGAATCATACGGTGACCTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_2_A
GTACATGAATCATACGTCACACTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_2_T
GTACATGAATCATACGTCACTCTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_2_G
GTACATGAATCATACGTCACGCTGTCCNNNNNNNNACCCATACGT
>left_to_insert_db_2_C
GTACATGAATCATACGTCACCCTGTCCNNNNNNNNACCCATACGT

**Comment by AdilyAid** [comment]
May be the 'N's do the problem?

**Comment by quito418** [comment]
I reproduced the error (the error is related to empty models in the partial layer of P-RMI, which happens when the reference is small).

I will ping you after the fix until tomorrow.

**Comment by AdilyAid** [comment]
Thank you!

**Comment by quito418** [comment]
Hi Adily,

I fixed my code and it runs well in my test environment. (Built index, Ran alignment with your reference file with random reads, repeated multiple times)

Can you check if the recent commit works?(it is not yet updated in Bioconda)

Thank you

**Comment by AdilyAid** [comment]
Hello,

I pulled the changes:
```
~/soft/BWA-MEME$ git pull
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 9), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (12/12), 1.83 KiB | 117.00 KiB/s, done.
From https://github.com/kaist-ina/BWA-MEME
   258fa85..9751b4b  master     -> origin/master
Updating 258fa85..9751b4b
Fast-forward
 RMI/rmi_lib/src/train/two_layer.rs | 11 ++++++++++-
 src/LearnedIndex_seeding.cpp       | 16 +++++++++++++++-
 src/fastmap.cpp                    |  4 +++-
 3 files changed, 28 insertions(+), 3 deletions(-)
```
But got the same killed message:
```
~/runs/20220719/bwa-meme$ ~/soft/BWA-MEME/build_rmis_dna.sh db_8_adaptors_left.fasta
Training top-level pwl model layer
Training second-level linear model layer (num models = 268435456)
/home/user/soft/BWA-MEME/build_rmis_dna.sh: line 39: 3251394 Killed                  bwa-meme-train-prmi --data-path $DIR_NAME $DATA_PATH $DATA_NAME pwl,linear,linear_spline 268435456
```
What do you think? I really appreciate your help.

**Comment by quito418** [comment]
Have you also installed the Conda version of BWA-MEME in the server?

If so the script would be using the Conda train command, which is not a fixed version. 

Or it could be the memory issue, I just checked the memory usage, the peak memory usage is about 70GB (memory usage is similar to human)

**Comment by AdilyAid** [comment]
Yes, the BWA-MEME is installed also by Conda. But I run the script from the project I cloned from git

**Comment by quito418** [comment]
Can you tell me the size of the server memory?

In the latest commit, I also updated the execution priority of conda script and local built script. You can ignore the installed Conda version BWA-MEME, just make sure you run `build_rmis_dna.sh` in the BWA-MEME folder.

**Comment by AdilyAid** [comment]
total        used        free      shared  buff/cache   available
Mem:    15           8           6           0           0           6
Swap:    1           1           0

I pulled also the changes at the build_rmis_dna.sh script

**Comment by quito418** [comment]
I guess it is the result of `free -g` 

So, is there 15 GB of memory available on your server? If so, it might not be possible to build the index in your server unless using the swap memory.

For human reference, you can download the indices and the trained models from https://web.inalab.net/~bwa-meme/.

**Comment by AdilyAid** [comment]
Thank you very much for your help.
