### ISSUE TITLE
training for other genomes, e.g. bacteria genome error

### ISSUE THREAD

**Issue by jianshu93** [kaist-ina/BWA-MEME#12]
Dear bwa-meme team:

when using bacterial genome as reference I have the following error (genome are highly fragmented and are assembled from meagenome):

(base) [jzhao399@login-phoenix-3 Competitive_mapping]$ build_rmis_dna.sh ./all_mags_rename.new.fasta
Training top-level pwl model layer
Training second-level linear model layer (num models = 268435456)
[2nd layer]Computing lower bound stats...
[2nd layer]Fixing empty models...
Computing last level errors...
Average gap: 0.8713072761893272
Total Partial model num: 0, Leaf of partial model num: 0
Total last layer model num: 268435456
Partial start at idx:268435456
Model build time: 103312 ms
Average model error: 1.914389257033157 (0.0000020606146782561575%)
Average model L2 error: 78.10451166276728
Average model log2 error: 1.9188643583795388
Max model log2 error: 7.189824558880018
Max model error on model 79172320: 146 (0.0001571518132585239%)
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', rmi_lib/src/codegen.rs:399:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Any idea? I installed everything via condo,

Thanks,

Jianshu

**Comment by quito418** [comment]
Hi, thank you for reporting the error.

I just fixed this issue in the recent commit 3028bc0f3b8f65ad8010c223cd53dc5db65e60e7. 
You may be able to run BWA-MEME with the recent commit.

I will update the Bioconda package soon (1-2 day) after I fix another issue. 

Thank you

**Comment by jianshu93** [comment]
Hello,

training was successful but core dumped when mapping:

[jzhao399@atl1-1-02-003-5-r Competitive_mapping]$ bwa-meme mem -7 -t 12 -o all_fasta_meme.sam ./all_mags_rename.new.fasta T4AerOil_R1.fa T4AerOil_R2.fa
Looking to launch executable "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/bin/bwa-meme_mode3.avx512bw", simd = _mode3.avx512bw
Launching executable "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/bin/bwa-meme_mode3.avx512bw"
-----------------------------
Executing in AVX512 mode!!
-----------------------------
* SA compression enabled with xfactor: 8
* Ref file: ./all_mags_rename.new.fasta
* Entering FMI_search
Reading other elements of the index from files ./all_mags_rename.new.fasta
* Index prefix: ./all_mags_rename.new.fasta
* Read 0 ALT contigs
* Reading reference genome..
* Binary seq file = ./all_mags_rename.new.fasta.0123
* Reference genome size: 92903796 bp
* Done reading reference genome !!

------------------------------------------
1. Memory pre-allocation for Chaining: 1703.8604 MB
2. Memory pre-allocation for BSW: 2875.4043 MB
[M::memoryAllocLearned::MEME] Reading Learned-index models into memory
[Learned-Config] MODE:3 SEARCH_METHOD: 1 MEM_TRADEOFF:1 EXPONENTIAL_SMEMSEARCH: 1 DEBUG_MODE:0 Num 2nd Models:268435456 PWL Bits Used:28
[M::memoryAllocLearned::MEME] Loading RMI model and Pac reference file took 5.331 sec
[M::memoryAllocLearned::MEME] Reading suffix array into memory
[M::memoryAllocLearned::MEME] Loading pos_packed file took 5.675 sec
[M::memoryAllocLearned::MEME] Generating SA, 64-bit Suffix and ISA in memory
[M::memoryAllocLearned::MEME] Runtime-build-index took 1.483 sec
3. Memory pre-allocation for BWT: 657.5362 MB
------------------------------------------
* Threads used (compute): 12
* No. of pipeline threads: 2

[0000] read_chunk: 120000000, work_chunk_size: 120000263, nseq: 1019142
	[0000][ M::kt_pipeline] read 1019142 sequences (120000263 bp)...
[0000] Reallocating initial memory allocations!!
[0000] Calling mem_process_seqs.., task: 0
[0000] 1. Calling kt_for - worker_bwt
[0000] read_chunk: 120000000, work_chunk_size: 120000132, nseq: 1044040
Segmentation fault (core dumped)


without -7 option, it was successful and the same with BWA-MEM2. Can you please provide an email so that I share those reads and reference genome with you?

Thanks,

Jianshu

**Comment by quito418** [comment]
Sure, can you send the files to tom418@kaist.ac.kr, 

Thank you!

**Comment by quito418** [comment]
Dear Jianshu,

Can you please send the files to quito418.mail@gmail.com?

Thank you

**Comment by quito418** [comment]
In the recent commit 9751b4bd50c4126db63a8d8886a87a5c8782bc92,  we fixed the error in BWA-MEME which might be related to your case.

We also tested BWA-MEME works without `segmentation fault` in 4 randomly chosen bacteria genomes. ( https://www.ebi.ac.uk/ena/browser/view/GCA_000226275, https://www.ebi.ac.uk/ena/browser/view/GCA_000512185, https://www.ebi.ac.uk/ena/browser/view/GCA_000300175, https://www.ebi.ac.uk/ena/browser/view/GCA_000021305)

Please reopen this issue and let us know if you still have the same error.

Thank you
