### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by a00101** [kaist-ina/BWA-MEME#13]
First, thank you for developing nice tool.

I got an error while indexing human genome.

Step1. FASTA index
 - results 6 files (genome.fasta.0123, *.amb, *.ann, *.pac, *.pos_packed, *.suffixaray_uint64)
 
Step2. build rmis
 - cmd: `build_rmis_dna.sh genome.fasta`
 - output is below.

```
Training top-level pwl model layer

Training second-level linear model layer (num models = 268435456)

[2nd layer]Computing lower bound stats...

[2nd layer]Fixing empty models...

Computing last level errors...

Average gap: 19.046705737228734

Total Partial model num: 41300812, Leaf of partial model num: 186417

Total last layer model num: 309549851

Partial start at idx:268249039

Model build time: 867524 ms

Average model error: 1494.9997627890018 (0.00002420435750882617%)

Average model L2 error: 42821253900152.66

Average model log2 error: 5.169317311164392

Max model log2 error: 18.635250483499124

Max model error on model 309539124: 407164 (0.006592069956143941%)
```

I wish you would help me. thank you.

**Comment by quito418** [comment]
Hi, 

The output you posted only contains a log about the accuracy statistics of models.

Can you tell me if there are files with suffix `*.suffixarray_uint64_L0_PARAMETERS`? (based on the your command, file should be something like `genome.fasta.suffixarray_uint64_L0_PARAMETERS`)

If those files exist, you might have successfully trained the model.
If the file does not exist, please share the subsequent part of the log you posted.

Thanks

**Comment by a00101** [comment]
@quito418 
Thank you for your rapid reply.
Yes, as you said, three files are generated such as 'genome.fasta.suffixarray_uint64_L0, L1 or L2_PARAMETERS'.


I think this command have worked done right.
Thank you.

**Comment by quito418** [comment]
Great! let me know if you have other questions.
