### ISSUE TITLE
Error compile from source

### ISSUE THREAD

**Issue by giusmar** [kaist-ina/BWA-MEME#17]
Hi,
i'm trying to compile from source bwa-meme with the command:

```bash
sudo make -j 32
```

but i have this error and i don't know how to resolve. Can you help me, please?

[error.log](https://github.com/kaist-ina/BWA-MEME/files/10448477/error.log)

I'm working on e2-standard-32 google machine type

**Comment by quito418** [comment]
Hi, 

[This](https://github.com/bwa-mem2/bwa-mem2/pull/205#issue-1269276017) fixes the issue!

I updated the code, you can pull the change and retry compiling.

Please let me know if there is another issue.

**Comment by giusmar** [comment]
TY
Now it is working, but now i've another issue. I'll open another 3d. :)
