### ISSUE TITLE
Indexing Human Genome

### ISSUE THREAD

**Issue by giusmar** [kaist-ina/BWA-MEME#19]
Hi,
I'm trying to make the index for human genome fasta GRCh38.p14 and i've setted this command:

```bash
bwa-meme index -a meme -t 16 -p bwa-meme/bwa-meme_GRCh38.p14_genomic.fna fasta/GRCh38.p14_genomic.fna
```

But it still use one single core for processing. Can you help me please?

**Comment by quito418** [comment]
Hi, 

Index building is partially multi-threaded,

In particular, suffix array building with `saisxx` function is single-threaded and building indexes for BWA-MEME is multi-threaded.

In total, it should take between 1~2hour with 16 threads for the human genome.
(In my local environment, it took 30min for suffix array building)

**Comment by giusmar** [comment]
Thank you for explaining me these steps :) we can delete this issue directly hehe
