### ISSUE TITLE
stable issue or memory error for 

### ISSUE THREAD

**Issue by huangl07** [kaist-ina/BWA-MEME#24]
hello ,when I using 1.06 version to do bwa-meme some how like that
" bwa-meme mem  -M -a -t 8 $2 $3 $4 |mbuffer -m 8G |samtools sort --reference $2 -o $5.cram -O CRAM -@ 8 -"

but it turns out exit without any error report?

how could it be?

**Comment by quito418** [comment]
Hi, 

Can you elaborate more in the log?

It would be helpful if you attach the log output.

In my local environment, I get something like this.

![image](https://github.com/kaist-ina/BWA-MEME/assets/26645270/76216730-0fe8-4d54-9eea-be65c8aa0912)

**Comment by huangl07** [comment]
well，when I not using the “|” flag，it all run ok，I think maybe is cause by IO

**Comment by quito418** [comment]
Great, if you have any more problems related to this, please reopen this issue.
