### ISSUE TITLE
Unable to run the alignment

### ISSUE THREAD

**Issue by rpresingu** [kaist-ina/BWA-MEME#25]
I have generated the indexes and model but when i try to run the command i see the following error:

(base) administrator@mastry1:/data2/raju/BWA-MEME$ ./bwa-meme mem -Y -K 100000000 -t 64 Homo_sapiens_assembly38.fasta  D1_S1_L001_R1.fq -o output_mem2.sam
Looking to launch executable "/data2/raju/BWA-MEME/./bwa-meme_mode3.avx", simd = _mode3.avx
Launching executable "/data2/raju/BWA-MEME/./bwa-meme_mode3.avx"
-----------------------------
Executing in AVX mode!!
-----------------------------
* SA compression enabled with xfactor: 8
* Ref file: Homo_sapiens_assembly38.fasta
* Entering FMI_search
ERROR! Unable to open the file: Homo_sapiens_assembly38.fasta.bwt.2bit.64

It says Homo_sapiens_assembly38.fasta.bwt.2bit.64 file but iam using the original reference file.

Please help.

Thanks

-Raju

**Comment by quito418** [comment]
Hi Raju,

Your alignment command seems to miss "-7" option for running BWA-MEME.

Also, you may want to use `./bwa-meme_mode1 ` or `./bwa-meme_mode2` option to select different memory mode based on your server memory configuration.

` ./bwa-meme mem -Y -7  -K 100000000 -t 64 Homo_sapiens_assembly38.fasta D1_S1_L001_R1.fq -o output_mem2.sam`

If you wish to run paired read alignment, like its done in BWA and BWA-MEM2, just add second reads in argument.

` ./bwa-meme mem -Y -7  -K 100000000 -t 64 Homo_sapiens_assembly38.fasta D1_S1_L001_R1.fq <your second read> -o output_mem2.sam`

Best regards,
Youngmok Jung
