### ISSUE TITLE
这个arm64的分支怎么使用？构建还是报一样的错误

### ISSUE THREAD

**Issue by wwh131** [kaist-ina/BWA-MEME#26]
g++: error: unrecognized command line option ‘-msse’
g++: error: unrecognized command line option ‘-msse2’
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-mssse3’
g++: error: unrecognized command line option ‘-msse4.1’

**Comment by quito418** [comment]
Hi, unfortunately, the ARM64 version is under development and is not available currently.

**Comment by wwh131** [comment]
意思是不能在arm64上构建？

**Comment by quito418** [comment]
Yes, for now it can't be built for arm64.
