### ISSUE TITLE
Can't find the recipe on bioconda

### ISSUE THREAD

**Issue by gcambray** [kaist-ina/BWA-MEME#28]
Hi there,
When running `conda install -c conda-forge -c bioconda bwa-meme` conda (or mamba) can't find the package...
Same with the `search` command
Is the recipe not available anymore?

I tries to build fron source but I'm on macos and it is not straightforward. There are some posts related to bwa-mem2 that suggest some solutions but I didn't manage to get it to work yet. So a conda-based solution would save some headaches.

With thanks!

**Comment by quito418** [comment]
Hi there,

Thank you for reaching out and sharing your challenges with installing bwa-meme via conda/mamba and attempting to build it from the source on macOS. 

I must share that, as of now, we do not offer official support for macOS for this particular package.

Thanks!
