### ISSUE TITLE
Why is the size of the reference genome listed in the log different from the actual size?

### ISSUE THREAD

**Issue by nntake** [kaist-ina/BWA-MEME#30]
I ran bwa-meme. I was able to do it without any errors, but I have one question.

In the log, the reference genome size was 704480394 bp as shown below.
However, the real reference genome size is 326897438 bp. 
Why the difference?

* SA compression enabled with xfactor: 8
* Ref file: /home/・・・/・・・.fa
* Entering FMI_search
Reading other elements of the index from files /home/・・・/・・・.fa
* Index prefix: /home/・・・/・・・.fa
* Read 0 ALT contigs
* Reading reference genome..
* Binary seq file = /home/・・・/・・・.fa.0123
* Reference genome size: 704480394 bp
* Done reading reference genome !!

The Index file was created as follows

bwameme="/.../bwa-meme:1.0.6..."
ref="/home/... /....fa"

##make index
singularity exec ${bwameme} bwa-meme index -a meme ${ref} -t 1

##training
singularity exec ${bwameme} build_rmis_dna.sh ${ref}

Then I ran bwa-meme as following.

samtools="/…/samtools:1.17…"
TRGET_1=/…/…_1.fq.gz
TRGET_2=/…/…_2.fq.gz

singularity exec --bind /home/… ${bwameme} bwa-meme mem -M -R "@RG\tID:fname\tSM:$fname\tPL:Illumina\tLB:$fname_library_1" -7 -Y -K 100000000 -t 1 ${ref} ${TARGET_1} ${TARGET_2} | singularity exec --bind /home/… ${samtools} samtools view -bS > ${OUT_D}/$fname.bam

**Comment by quito418** [comment]
Hi Nonodayo,

The "Reference genome size" you are seeing is the length of 0123 file (i.e., Binary seq file).

It should be twice the size of your original reference file as it has reverse complement of reference bases in addition to reference genome.

Still there is a mismatch between 704480394 and 2 x 326897438, I suspect it is due to reference genome alt contigs or method used for measuring the reference genome size.

**Comment by nntake** [comment]
Dear quito418,

Thank you so much for your quick response!!!
I checked my reference genome size using seqkit and found that the actual genome size is 352240197. 
352240197 x 2 = 704480394
So the log should be OK!

**Comment by quito418** [comment]
Glad it helped! Closing the issue 😄
