### ISSUE TITLE
bioconda recipe?

### ISSUE THREAD

**Issue by nick-youngblut** [kaist-ina/BWA-MEME#4]
Given that bwa-meme will likely be a dependency for a a lot of bioinformatics tools/pipelines, it would be very helpful to have a bioconda recipe for bwa-meme, as are already available for [bwa](https://bioconda.github.io/recipes/bwa/README.html#package-bwa) and [bwa-mem2](https://bioconda.github.io/recipes/bwa-mem2/README.html#package-bwa-mem2).

Are there any plans on creating a bioconda recipe for bwa-meme?

**Comment by quito418** [comment]
Hi, 
Thank you for your suggestion.
We will work on bioconda recipe and make it available soon.

**Comment by quito418** [comment]
We now support Bioconda, instructions are updated in Readme.

Thanks
