### ISSUE TITLE
binary autoselect like bwa-mem2?

### ISSUE THREAD

**Issue by keiranmraine** [kaist-ina/BWA-MEME#5]
Is it possible to build all chipset binaries and have the tool auto-select the correct one for the system it is running on in the same way as the original bwa-mem2 works?

https://github.com/bwa-mem2/bwa-mem2#installation

Without this I'm not convinced a bioconda version will be as useful.

**Comment by quito418** [comment]
Thank you for your interest!

We are going to add "-mode" option in BWA-MEME executable.

Then, users may be able to choose the mode of BWA-MEME according to their RAM size.

(I assume you meant the mode should be supported with a single binary executable, current BWA-MEME in Bioconda supports various chipsets but with a mode that requires 118GB RAM size)

+ we will add bioconda installation is available once we add the mode option

**Comment by keiranmraine** [comment]
I was meaning the avx512, avx2, SSE4.2 binary selection, I was thrown off by the requirement to build each individually rather than a `make multi` directive, but it appears you have this covered.
