### ISSUE TITLE
bioconda bwa-meme-train

### ISSUE THREAD

**Issue by keiranmraine** [kaist-ina/BWA-MEME#6]
I understand the reasons for not including everything in the main recipe but it would be very useful to provide the tools for training.

I'm making the assumption that training is required to use Human GRCh38 (with alts suitable for bwakit).  It will make this far more attractive for groups with a diverse species/build requirement.

BTW I'm actually looking at this to do a bake-off against NVIDIA parabricks, specifically as the implementation doesn't allow for use of `bwa-postalt.js` or any other modifications due to the heavy cost/effort required to change it.

**Comment by quito418** [comment]
That's a good suggestion.

We also believe it may be much convenient for users if we provide an executable for training.

As suggested, in the next version we will also support command for training (learned-index train) in the Bioconda package.

**Comment by quito418** [comment]
We added training binary into bioconda package. Readme is updated according to the update.

Thanks
