### ISSUE TITLE
Q: `-K` value

### ISSUE THREAD

**Issue by keiranmraine** [kaist-ina/BWA-MEME#7]
Is the very large value of `-K 100000000` (100 mill) used for a specific reason?  Initially this was to prevent variability when specifying different numbers of threads.

The [parabricks comparison command](https://docs.nvidia.com/clara/parabricks/v3.5/text/fastq_and_bam_processing.html#compatible-cpu-based-bwa-mem-gatk4-commands) indicates`10000000` (10 mill).

Would a 10 million value work without any detriment to run time?

**Comment by quito418** [comment]
The K option is used just to compare the SAM output result.

I remember there were no significant differences in performance with regard to the K value (you can just remove the K option).

By the way, If you are running BWA-MEME with more than 36 physical cores ( 72 vCPU), we recommend using [mimalloc](https://github.com/microsoft/mimalloc) for performance.

**Comment by keiranmraine** [comment]
Thanks, I was just looking at the mimalloc.  Although I probably won't exceed 36 is there any reason not to include the mimalloc library in the conda build?

FYI: 1.0.2 isn't actually available via conda yet due to: https://gitter.im/bioconda/Lobby?at=62667d54c61ef0178edb5a87

**Comment by quito418** [comment]
Using mimalloc has no improvement in performance with cores less than 36, while it requires much more runtime memory.

In case of many cores, [malloc in glibc affects the multithreaded performance](https://twitter.com/Hasindu2008/status/1051798732822335488?s=20).

Instead of changing overall implementation, we decided to use ```LD_PRELOAD=/usr/bin/libmimalloc.so  bwa-meme <options>```.

Thanks for the update, I was also wondering why the new bwa-meme version was not available.

**Comment by keiranmraine** [comment]
I understand the use of `LD_PRELOAD`, used it with [gperftools](https://github.com/gperftools/) `tcmalloc_minimal` on the legacy bwa for ~8% speedup on modest threads (>12 IIRC).

I was more meaning install the library as part in the conda package so that it could be easily available, also very beneficial for containerised builds based on conda.

**Comment by quito418** [comment]
Thats a good suggestion, I will include it in the  package!

**Comment by AJ-Guo** [comment]
> Thats a good suggestion, I will include it in the package!

Hi~, Thank you for your nice work. I was wondering how could i speed up running with 64 threads (memory is 512GB) in command line? 
Now, my command line look like below:

bwa-meme mem -7 -a -Y -K 200000000 -t $THREADS $OUTPUT_DIR/reference.fasta $R1 \
      | mbuffer -m 60G \
      | samtools view -F 8 -u \
      | samtools sort -@ 64 -m 3G --output-fmt bam,level=1 -o $OUTPUT_DIR/S.bam

**Comment by quito418** [comment]
Hi Anjie, 

The command line looks good as it is. I am not sure changing value for `-K` would have difference compared to using default setting.

1. My suggestion would be looking into run stats and see which of computation or disk usage is a bottleneck in your set-up. Try to maximize the computation throughput at the same time make sure the disk IO time is hidden during the bwa computation pipeline. (bwa has 2 parallel pipeline that runs 1. seeding, 2. extension, 3. output sam result, where 1 and 2 is computation heavy and 3 is disk IO heavy)
2. I suggest mbuffer memory has the same value as thread x memory in samtools sort command. In your case, if we assign 60G for mbuffer, I would use something like "-@ 60 -m 1G".

Thanks!
