### ISSUE TITLE
Resource requirements for build_rmis_dna.sh

### ISSUE THREAD

**Issue by keiranmraine** [kaist-ina/BWA-MEME#9]
What are the resource requirements for the `build_rmis_dna.sh` script:

* Threads/cpus (1?)
* Memory
* Approx runtime

**Comment by quito418** [comment]
In my `Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz`  machine.

It uses 1 thread, maximum 72GB of resident memory, about 15 min to finish RMI training.

I am not sure about the maximum resident memory, as train code uses mmap to load training data into memory (which should be the most of the resident memory). 

Please let me know if you need an accurate number for memory usage.
